### ISSUE TITLE
Can you make this deployable to heroku?

### ISSUE THREAD

**Issue by askfriends** [AnshumanFauzdar/telegram-bot-heroku-deploy#4]
Hello;
Im noob as u said and i want to deploy this app to heroku, can u do that?
https://github.com/CrypticSignal/av-converter

**Comment by AnshumanFauzdar** [comment]
@askfriends you can use [this](https://github.com/AnshumanFauzdar/telegram-bot-heroku-deploy#if-you-are-trying-to-lazy-which-you-should-not-deploying-to-heroku)
